### ISSUE TITLE
Roadmap for MailWatch

### ISSUE THREAD

**Issue by asuweb** [mailwatch/MailWatch#491]
There has been a lot of activity in updating and upgrading V1.20 ready for stable release, which is fantastic, but I wonder if perhaps we are concentrating too much on cosmetic changes to the UI / code base, rather than actually stabilising the release so we can move on to V2.0?

As far as I know, V2.0 will be a full UI overhaul, and the quicker V1.20 becomes stable, the quicker progress can be made on V2.0.

I'll tow the line and contribute to whatever the plan is, but can we have some clarity as to what we (as in MailWatch) actually want to achieve, so that we can work in a unified and cohesive manner?

Just my thoughts, would be interested to hear from @Skywalker-11 @endelwar @stefaweb on this.

**Comment by stefaweb** [comment]
What we currently have in PR is fine for me and we must consecrate to empty it, do QA and publish. 

But we must stop to add feature or we will never publish RC5 (or 1.20. final)...

**Comment by endelwar** [comment]
This is my view for 1.2.0:

- [x] Resolve everything in [this milestone](https://github.com/mailwatch/1.2.0/milestone/1) list (something is already done, and will be offlist as soon as I merge develop into master with next RC)
- [x] Make a last RC (maybe RC5 or RC6) for real (not like the last 4 RC 😝)
- [x] Ask for testing in mailing list and EFA project (@shawniverson hi there!)
- [x] Fix everything that is broken
- [x] Release finally a stable 1.2.0
- [x] Rename github repository from `mailwatch\1.2.0` to `mailwatch\mailwatch` and create a 1.2 branch
- [x] Publish news on web site & drink some 🍻
- [x] Merge new features already done in 1.2 branch
- [x] Release only bug and security fixes for 1.2

New features are welcome, as always, but don't have to be a priority for release.

For 2.0 I'm going to open a new brainstorming thread on a new issue.

**Comment by endelwar** [comment]
Of course I'm open to discussion on what should or should not be part of 1.2.0, let's use this thread!

**Comment by asuweb** [comment]
@endelwar - That is what I was think along the lines of as well, but it's good to have it written down.

I think it's best if we leave it at that list, and get to a point where 1.2 is stable and only open for bug fixes, and then it frees up time to work on the new 2.0.

I think all cosmetic changes / nice to have but not essential (those that currently work but might not be so pleasing to the eye etc) should be left alone - there's a nice saying in English - if it isn't broken, don't fix it (it probably translates to all languages).

I feel that all of the little changes have a risk of inducing new bugs, which will then need fixing again, which will then need testing, and then need fixing etc, etc - we will end up never getting out of the cycle.

**Comment by stefaweb** [comment]
These PR should be in the 1.2 list for me:

#487
#474
#473
#471
#468
#425
#419

Optional:

#477
#435

**Comment by stefaweb** [comment]
Hello @endelwar,
Could you please push #468, #425 and #473 if all is ok?

**Comment by stefaweb** [comment]
Hello! News from the PR basket.

#487 New tools and cron modifications
Should be close to be ok. The last thing done was to add new test for functions.php path in all php files.

#471 New upgrade.php 
All request done. Stay the version printed. Currently, I use version from functions.php. Do you want it or NO version at all?

#425 Fixes for Mailwatch.pm, SQLBlackWhiteList.pm and SQLSpamSettings.pm for utf8mb4
Ok for me. 
Needed for full utf8mb4 flux.

**Comment by stefaweb** [comment]
Hello @endelwar,
Can you merge the PR queue if you are available?

**Comment by stefaweb** [comment]
It starting difficult to find a bug (or a cosmetic problem) in develop.  😀

**Comment by stefaweb** [comment]
In fact Yes, #533 deserve to be looked after.

Do you have others, I will have forgotten?

**Comment by stefaweb** [comment]
Hello @endelwar,

Can you merge the PR queue if you are available?

#602, #599, #571, #558

If ok, #597

**Comment by stefaweb** [comment]
Great for RC5! 

https://github.com/mailwatch/1.2.0/releases

If you need help again for mailwatch-docs, let me know. The 4 pages are in the PR queue.

**Comment by endelwar** [comment]
1.2.0 is out!
A lot of work on fixing vulnerabilities has been done thanks to the work of @shawniverson and @darky83

**Comment by stefaweb** [comment]
Great!
The PR with security fixes is impressive.

**Comment by stefaweb** [comment]
Bug Contest for 1.2.1 !   😀

**Comment by asuweb** [comment]
Slight shame we didn't test the final release - we'll get though

**Comment by shawniverson** [comment]
Yeah, that's my fault.  Some of these I would have caught after merging the security stuff, but I tested prior to the merge, not after.  Got in a hurry :(

I'm going to do the following (hopefully tonight):

1.  Create separate error messages for validation and token failures (sorry, dog, you gotta go)
2.  Cleanup styling as I go
3.  Create a mechanism for viewmail.php to allow quarantine reports access safely

**Comment by asuweb** [comment]
No worries @shawniverson - the security updates were definitely needed.

**Comment by stefaweb** [comment]
We can may be wait until the end of the week-end to publish 1.2.1... to be sure to do not found a last minute problem...

**Comment by stefaweb** [comment]
Hello!
Can you publish 1.2.3 for the end of the week if all is ok?
I would like to take advantage of this long week-end to update my prod server still in RC5?   😇

**Comment by endelwar** [comment]
I think I'm going to release 1.2.3 today around 17:00 UTC, is everything ok on testing side?

**Comment by stefaweb** [comment]
Seems fine for me.

Just add #820 and #818 if Ok.

**Comment by stefaweb** [comment]
Hello @endelwar!

You can may be publish 1.2.5?

The curent develop code is very stable and correct a important bug in the upgrade.php script.
